### ISSUE TITLE
I can't download your Pretrained model.

### ISSUE THREAD

**Issue by chamsuzuki** [MortenHannemose/pytorch-vfi-cft#1]
I tried download the model but my browsers are said 'connection timeout'.
How to get that?

Thank you.

**Comment by chamsuzuki** [comment]
I was able to download the file now.
Thank you very much.

**Comment by pstetz** [comment]
I have the same issue.  The link

http://people.compute.dtu.dk/mohan/vfi-cft/VFI_CFT_weights.pt.gz

is not working, I tried `wget` and finding an alternative link by searching DTU's website, however neither were successful.  Also tried both Firefox and Chrome

**Comment by MortenHannemose** [comment]
There was a power outage on the servers hosting the website around the time you had the issue.
Please let me know if it's working now.
In any case, I have also added an alternative link.

**Comment by pstetz** [comment]
Everything's working now, great, thank you!
