### ISSUE TITLE
how to change the resolution

### ISSUE THREAD

**Issue by L0kus1** [MortenHannemose/pytorch-vfi-cft#13]
how to change the resolution? My video is 1920x1080 but output is 320x168

**Comment by MortenHannemose** [comment]
Please look at the output printed when you run the command.
The code is very slow to run without a graphics card, so the default is to decrease the resolution to make it feasible.
Feel free to comment out the offending line https://github.com/MortenHannemose/pytorch-vfi-cft/blob/ab42b475b408755d7d430c3cd5dbc00403fcf2f4/slow_movie.py#L66
or run it with a GPU, for example in google colab.
