### ISSUE TITLE
How to train a model?

### ISSUE THREAD

**Issue by InzGIBA** [MortenHannemose/pytorch-vfi-cft#3]
Thank you for your work. But can you tell me how I can train my own model?
I want to use this project to increase the FPS from 30 to 60.
Accordingly, in various projects: _cartoons / anime / video_.

**Comment by MortenHannemose** [comment]
You can use the pretrained model for increasing from 30 to 60 FPS. I would expect the model to generalize to anime/cartoons (it's already trained on video), but if not feel free to train your own. 
Explaining how to train the model is explained in the paper, and the cyclic fine-tuning also contains some code for training the model. 
I wish you the best of luck with your project.

**Comment by xiaozhi2015** [comment]
Have you trained it successfully? @InzGIBA 
I have trained it according to paper while the ghosting phenomenon is quite serious.
Can you give some advice in training or will you release train code some time? @MortenHannemose
