### ISSUE TITLE
frame rate convertion ideas

### ISSUE THREAD

**Issue by igitlin** [MortenHannemose/pytorch-vfi-cft#4]
Very interesting result. Is it possible to make frame rate conversion based on your algorithm? from 24 to 25, and from 25 to 24. But you also need to take into account the change of scenes in the original video, so that the completed frames do not fall on the cuts.

**Comment by MortenHannemose** [comment]
24 to 25 fps can only be done approximately with our method, as the frame-rate can only be doubled, but you can get arbitrarily close. 
Conversion from 30 to 24 fps can be done exactly.
Yes you would need to handle cuts.
