### ISSUE TITLE
Custom Input Resolutions?

### ISSUE THREAD

**Issue by saturn118** [MortenHannemose/pytorch-vfi-cft#7]
Is it possible to provide different resolution input videos to this? Whenever I try anything other than the example resolution of width = 584, height = 388 it crashes

**Comment by Mcmartelle** [comment]
I've been able to get 1280x720 videos to work, however not with --cft true. The main error I get is "not enough GPU memory". I'm using a GTX 980 with 4GB of RAM.

**Comment by saturn118** [comment]
> I've been able to get 1280x720 videos to work, however not with --cft true. The main error I get is "not enough GPU memory". I'm using a GTX 980 with 4GB of RAM.

Thanks for responding so quickly. 

Yeah, it turned out to be the memory issue. I'm on card with 2GB of RAM and I cant process anymore than 3 frames at 720p before running out of memory, even with the --ctf flag turned off. Do you know if there's any way to circumvent this, maybe by regularly flushing the cuda memory or perhaps having it run exclusively on the cpu?  I tried setting all of the 'torch.cuda.is_available()' checks to 'False' to force it to run on the CPU but the it seems to cause it to freeze, using the 'simple_example.py' example

**Comment by Mcmartelle** [comment]
> I'm on card with 2GB of RAM and I cant process anymore than 3 frames at 720p before running out of memory

That's interesting, with my 4GB RAM GPU and a 720p video it can hit the 220 frames cap and process them all just fine. Maybe it loads a different subset of the "weights" data for each resolution, and the weights for bigger resolutions need more RAM.

With "--cft true" on a 720p video it tried to allocate 67GB of GPU memory, I'm not sure what's going on there.

**Comment by MortenHannemose** [comment]
If it is able to process just a few frames, there should be no limit on the length of video you can run it on. 

When I run on rain.mp4  (which is 720p) with cft enabled, I use an additional 3261mb memory on my GPU. (but I have never tried running it on a gpu with less than 11GB). Maybe @saturn118 has a higher baseline RAM usage on the GPU. 

There is only one version of the weights that's used for all resolutions. The additional memory usage is only from the frames. 

If you change ALL torch.cuda.is_available() to False, it should run exclusively on CPU, but be extremely slow. I would advise you to check it on a 180p video without CFT.

**Comment by Mcmartelle** [comment]
I see. Thank you for clarifying.
