### ISSUE TITLE
when there are harsh cuts in movies, it tries to interpolate but it ends up looking weird

### ISSUE THREAD

**Issue by deama** [MortenHannemose/pytorch-vfi-cft#9]
So basically when watching movies, whenever there's a cut, the algorithm tries to interpolate it, but it ends up making things worse, is there some way you could make it stop doing that during harsh cuts? Like add in a check to the python script or something?

**Comment by MortenHannemose** [comment]
I agree with your observations. We do not handle scene cuts, as that was not the focus of the project. You can use another method to detect them, and then give this code only frames without cuts.
